import type { Metadata } from "next";
import { Geist, Geist_Mono, Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";
import { TooltipProvider } from "@/components/ui/tooltip";
import { Theme, ThemeProvider } from "@/contexts/ThemeContext";
import { ConvexClientProvider } from "./convexdb/ConvexProvider";
import { cookies } from "next/headers";

const jakartaSans = Plus_Jakarta_Sans({
  variable: "--font-Jakarta-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const cookieStore = await cookies();
  const savedThemeState = (cookieStore.get("theme")?.value ?? null) as Theme | null

  return (
    <html lang="en" className={savedThemeState === 'dark' ? 'dark' : ''}>
      <head>

        <script dangerouslySetInnerHTML={{
          __html: `
                        (function() {

                            const saved = document.cookie.match(/theme=([^;]+)/)?.[1];

                            if (saved === 'dark') {
                                document.documentElement.classList.add('dark');
                            } else if (saved === 'light') {
                                document.documentElement.classList.remove('dark');
                            } else if (window.matchMedia('(prefers-color-scheme: dark)').matches) {
                                document.documentElement.classList.add('dark');
                            }
                        })()
                    `
        }} />
      </head>
      <body
        className={`${jakartaSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider defaultTheme={savedThemeState}>
          <TooltipProvider>
            <ConvexClientProvider>{children}</ConvexClientProvider>
          </TooltipProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
