import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import AppSidebar from "@/components/Sidebar";
import Header from "@/components/Header";
import { SidebarProvider } from "@/components/ui/sidebar";
import { preloadQuery } from "convex/nextjs";
import { api } from "@/convex/_generated/api";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function DashboardLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const preloaded = await preloadQuery(api.queries.boards.getAll);

    return (
        <SidebarProvider>
            <div className="w-full h-full">
                <Header />
                <div className="flex">
                    <AppSidebar preloadedBoards={preloaded} />
                    <main className="w-full duration-300 ease-in-out transition-all min-h-ful bg-dashboard-bg">
                        {children}
                    </main>
                </div>

            </div>
        </SidebarProvider>

    );
}
