import type { Metadata } from "next";
import AppSidebar from "@/components/AppSidebar";
import Header from "@/components/Header";
import { SidebarProvider } from "@/components/ui/sidebar";
import { preloadQuery } from "convex/nextjs";
import { api } from "@/convex/_generated/api";



export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

import { BoardProvider } from "@/contexts/BoardContext";

export default async function DashboardLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {

    const preloaded = await preloadQuery(api.queries.boards.getAll);

    return (
        <SidebarProvider>
            <BoardProvider preloadedBoards={preloaded}>
                <div className="w-full min-h-screen">
                    <Header />

                    <div className="flex h-[calc(100vh-4rem)]">
                        <AppSidebar />

                        <main className="w-full p-4 duration-300 ease-in-out transition-all  overflow-auto bg-dashboard-bg">
                            {children}
                        </main>
                    </div>

                </div>
            </BoardProvider>
        </SidebarProvider>

    );
}
